#! /bin/bash

run_dir=$(dirname "$0")
history_file="$run_dir/history.log"
pushd "$run_dir" > /dev/null || exit 1
source load_secrets
export DISPLAY=:0

# eo1 GPU is limited to a single fullscreen process
_pkills() {
  pkill -o chromium
  pkill evince
}

_display_on() {
  xset -dpms
}

_random_museum() {
    museums=("harvard.py" "rijks.py")
    num_museums=${#museums[@]}
    random_index=$((RANDOM % num_museums))
    echo "${museums[$random_index]}"
}

case "$1" in
  "on")
    _display_on
    echo 'display on'
    ;;
  "off")
    xset dpms force off
    echo 'display off'
    ;;
  "brightness")
    _display_on
    echo "$ROOT_PW" | sudo -S ./brightness "$2"
    ;;
  "art")
    _pkills
    _display_on
    selected_museum=$(_random_museum)
    echo "$selected_museum"
    /usr/bin/python3 "$selected_museum"
    chromium-browser frame.html --start-fullscreen &> /dev/null &
    # open frame.html
    ;;
  "news")
    _pkills
    _display_on
    ./news
    ;;
  "photo")
    _pkills
    _display_on
    ./photo
    ;;
  "favorite")
    # shellcheck disable=SC2016
    sed -i '${s/$/ FAV/}' "$history_file"
    ;;
  "today")
    awk '{ print $2 }' history.log
    ;;
  *)
    echo 'invalid input'
    ;;
esac

popd > /dev/null || exit 1
