#!/bin/bash

export DISPLAY=:0

# Get the script's directory
script_dir=$(dirname "$0")

# Change the directory to the script's directory using pushd
pushd "$script_dir" > /dev/null || exit 1

pkill evince

echo "sleeping..."
sleep 1

echo "remove yesterday..."
rm "${pdf}"

echo "download today..."
/usr/bin/wget "https://static01.nyt.com/images/$(date +"%Y/%m/%d")/nytfrontpage/scan.pdf"

echo "open fullscreen..."
/usr/bin/evince --presentation scan.pdf &

echo "done!"

# Switch back to the original working directory using popd
popd > /dev/null || exit 1
