#!/bin/bash

export DISPLAY=:0

sleep 1

echo "remove yesterday..."
rm scan.pdf

echo "download today..."
/usr/bin/wget "https://static01.nyt.com/images/$(date +"%Y/%m/%d")/nytfrontpage/scan.pdf"

echo "open fullscreen..."
/usr/bin/evince --presentation scan.pdf

echo "done!"
