#! /bin/bash

if [ "$EUID" -ne 0 ]; then
    echo "This script requires root, run it with sudo."
    exit 1
fi

set -eux

apt-get update

apt-get install -y --no-install-recommends \
  evince \
  cron \
  wget \
  python3.6 \
  libxcb-dri3-dev \
  x11proto-dri3-dev \
  unclutter
  # curl \
  # kmscube \

# TODO: gradually change in cron, ie $ sudo tee /sys/class/backlight/backlight-pwm1/brightness <<< 6
# backlight control
# sudo cron, not user
# sudo nano /sys/class/backlight/backlight-pwm1/brightness
