#! /bin/bash
# NOTE : may need to increase the partition size to avoid running out of space during upgrade

if [ "$EUID" -ne 0 ]; then
    echo "This script requires root, run it with sudo."
    exit 1
fi

set -eux

journalctl --vacuum-time=2d
apt clean
apt autoremove

apt-get update
apt-get upgrade

apt-get install -y --no-install-recommends \
  evince \
  cron \
  wget \
  python3.6 \
  libgbm-dev \
  unclutter
  # libxcb-dri3-dev \       # im not sure if these helped webkit GPU issues
  # x11proto-dri3-dev \     # maybe install them if chrome is crashing a lot

# i spent so long troubleshooting cron
timedatectl set-timezone America/New_York

apt clean
apt autoremove
